export { default as Login } from './login'
export { default as Dashboard } from './dashboard'
export { default as FormPatient } from './formAddPatient'
export { default as ResultPatient } from './resultPatient'
export { default as ProfileHospital } from './profileHospital'
export { default as ListPatient } from './listPatient'
